### ISSUE TITLE
:Start and :Dispatch are not running expected foreman commands

### ISSUE THREAD

**Issue by sycobuny** [tpope/vim-dotenv#1]
# Expected Behavior
1. Running `:Start` in Vim, inside of tmux and in the directory of a project with both a `Procfile` and `.env`, will create a new window/pane in tmux that is running `foreman start`.
2. Running `:Dispatch` similarly, but only while editing the `Procfile` in particular, will run `foreman check` and output the results into a quickfix window which will automatically open.
# Actual Behavior
1. Running `:Start` with no arguments creates a new tmux window on a regular shell with no environment modifications.
2. Running `:Dispatch` while editing the `Procfile` runs a basic `make` command (which fails), and does not automatically open the Quickfix window (though the results **are** outputted there).
# Environment

I've written a more complete documentation of my current setup inside of the `README` file for a small demo application at https://github.com/sycobuny/demo-dotenv-error, but here are the highlights:

I'm running the latest version of the various plugins involved on OS X Yosemite, with the latest versions of Vim and tmux from MacPorts, and rbenv.  I also have an overly-elaborate Vim configuration setup [here](https://github.com/sycobuny/rcfiles/tree/2bdb8480c83174f683eb1deeadbd85a2b23c16c3/configs/vim), all loaded from a stripped-down `.vimrc` [here](https://github.com/sycobuny/rcfiles/blob/2bdb8480c83174f683eb1deeadbd85a2b23c16c3/configs/vimrc).

I haven't configured my own `.projections.json` files or manipulated `g:projectionist_heuristics` yet, and the automatically-created `g:projectionist_heuristics` at least looks right to me: `{'Procfile': {'Procfile': {'dispatch': 'foreman check'}, '*': {'start': 'foreman start'}}}`.

**Comment by tpope** [comment]
First step, check `b:projectionist`.

**Comment by sycobuny** [comment]
`b:projectionist` is just an empty dictionary: `{}`, should I be setting this to some value (or set of values) manually?

**Comment by tpope** [comment]
I see what is happening. It is failing on startup only. Try reloading the file.

**Comment by sycobuny** [comment]
That does indeed fix the problem! Thanks! So, does this seem to indicate that some of my configuration is set up in a way that prevents correct operation, and I need to remove some code to let it work properly with dotenv/projectionist?

**Comment by tpope** [comment]
Lemme know if that doesn't work.

**Comment by sycobuny** [comment]
Totally fixed it! Thanks! :+1:
