### ISSUE TITLE
Incorrect "No dotenv found"

### ISSUE THREAD

**Issue by rgrinberg** [tpope/vim-dotenv#2]
When I do the following:

``` vim
:Dotenv config/.env.dev
:Dotenv
```

Gives me `# No dotenv found` at the end.

However, once I do `$ mv config/.env.dev .env` and then `:Dotenv` works as expected.

**Comment by tpope** [comment]
Sounds like you're expecting `:Dotenv {file}` to remember the filename, which is not how it works.
