### ISSUE TITLE
How to load specific .env file on startup?

### ISSUE THREAD

**Issue by catmfoo** [tpope/vim-dotenv#5]
I have a `.env` file in my home folder. When working inside another project directory (that is also in my home folder) that has its own `.env` file, it seems like only the closest `.env` up the directory tree is sourced into vim. My goal is for the one in my home folder to be always sourced automatically.

I see that you can use `:Dotenv {dir}` to load a specific `.env` file interactively. How would I go about doing this automatically on vim startup?

I'm not very versed in vim script so apologies if this is trivial, thanks for any help!

**Comment by tpope** [comment]
`autocmd VimEnter * if exists(':Dotenv') | exe 'Dotenv! ~/.env' | endif`
